### ISSUE TITLE
Parallel processing and fsubset, sbt, or ss

### ISSUE THREAD

**Issue by bkmontgom** [SebKrantz/collapse#240]
Great package!

I am having problems with fsubset and/or ss running in parallel with my real data where I would get "Error in unserialize(node$con) : error reading from connection".
So then I reduced the problem to the below (reproducible, hopefully) example:
The errors on the my real data occur when using future instead of parallel also - I haven't retested with this small example.
The garbage that shows up is different for fsubset, sbt, or ss, but is always there for iterations sufficiently large.
This code works fine with subset.
```
library(parallel)
library(data.table)
library(collapse)
dt <- data.table(x = 4:6)
iterations <- 600000L
cl <- makeCluster(4)
cl |> clusterEvalQ({library(data.table);library(collapse)}) |> invisible()
cl |> clusterExport(list('dt'))
a <- cl |> parLapply(1:iterations, \(y) {
  dt <- dt |> fsubset(1:3 %in% (1L + (y - 1L) %% 3L))
  dt$x
})
# a is list of integers (4, 5, 6, 4, 5, 6, ...) until iterations is made large
# then garbage like below creeps in
which(sapply(1:iterations, \(i) typeof(a[[i]])) != "integer") |> print()
# [1] 105517 255217 405517 555817
lapply(which(sapply(1:iterations, \(i) typeof(a[[i]])) != "integer"), \(z) a[[z]]) |> print()
# [[1]]
# [1] f0 f1 f1 6e 00 00 00 00
# 
# [[2]]
# [1] f0 f1 f1 6e 00 00 00 00
# 
# [[3]]
# [1] f0 f1 f1 6e 00 00 00 00
# 
# [[4]]
# [1] f0 f1 f1 6e 00 00 00 00

sessionInfo() |> print()
# R version 4.1.2 (2021-11-01)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 19044)
# 
# Matrix products: default
# 
# locale:
#   [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
# [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
# [5] LC_TIME=English_United States.1252    
# 
# attached base packages:
#   [1] parallel  stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
#   [1] collapse_1.7.6    data.table_1.14.2
# 
# loaded via a namespace (and not attached):
#   [1] compiler_4.1.2 tools_4.1.2    Rcpp_1.0.8 
```

**Comment by SebKrantz** [comment]
Thanks! I think this error could occur because I am fetching a global option `getOption("collapse_DT_alloccol")` from C code inside `fsubset`, and perhaps fetching a global option in parallel does not work well. Can you verify for me that the problem also occurs if you are using a data frame and tibble instead of a data.table? As a background: data.table's are created in C as overallocated lists i.e. the number of elements in that list is greater than the number of columns in the data.table, but R is tricked by setting the 'length' attribute of that list in C to the amount of columns utilized. This allows data.table to add columns by reference `:=` without creating a shallow copy of the list and attributes (as is done for data.frames). This however also complicates programming with data.tables especially for packages like collapse that aspire to create valid data.tables without actually importing data.table.

**Comment by bkmontgom** [comment]
Correct, no problem with a data.frame or tibble.

**Comment by SebKrantz** [comment]
Ok, thanks. I'll leave the issue open and see if this can be solved in some way, but for the time being just use the quick converters `qDF` or `qTBL` to convert your data.table before the parallel statement and reconvert using `qDT` afterwards.

**Comment by bkmontgom** [comment]
Thanks.  I still have some joins and dt[expr, var1 := shift(.I), by = var2] that I can't replace with collapse inside the parallel function, so I'm going to stick with subset right now.  Any application I'm running in parallel and I don't need data.table, I'll do as you suggest.

**Comment by SebKrantz** [comment]
I've now pushed a development version of collapse that does not have the option anymore. On my mac system this works without error even with data.table's. You could install it using `remotes::install_github("SebKrantz/collapse", ref = "development")` and confirm.

**Comment by bkmontgom** [comment]
Thank you so much for the quick response to this.  Unfortunately that hasn't fixed the problem for me.  Both the toy example and my real problem still produce errors.
```
[1]  32760  34410 182460 184110 332760 334410 483060 484710
[[1]]
   x
1: 4

[[2]]
[1] 30 dc f1 6e 00 00 00 00

[[3]]
   x
1: 4

[[4]]
[1] 30 dc f1 6e 00 00 00 00

[[5]]
   x
1: 4

[[6]]
[1] 30 dc f1 6e 00 00 00 00

[[7]]
   x
1: 4

[[8]]
[1] 30 dc f1 6e 00 00 00 00
sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] collapse_1.7.7.9000 data.table_1.14.2  

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2    Rcpp_1.0.8

**Comment by SebKrantz** [comment]
Ok, thanks a lot for the feedback! I have found and fixed one possible alternative cause of the problem. If you could check this one more time on your system that would be much appreciated!

**Comment by bkmontgom** [comment]
I'm afraid that didn't help either.

**Comment by SebKrantz** [comment]
Ok, thanks!

**Comment by SebKrantz** [comment]
I'm still not able to reproduce your issue, but the current version just submitted to CRAN has some memory protection fixes included, so I think this issue could be solved now. Possibly you could check again, otherwise I'm inclined to close the issue.

**Comment by bkmontgom** [comment]
I reran the above code with 1.8.4 and the problem with up to 1e7 iterations.  I couldn't make it mess up anymore.  I think it's fixed!  Thank you.

**Comment by SebKrantz** [comment]
Ok, great! Thanks a lot also for flagging this and for repeated testing and giving feedback!
